---
version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/aura-di.configured.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/auryn.reflection.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/dice.configured.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/dice.reflection.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/laminas-servicemanager.reflection.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/laravel.configured.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/laravel.reflection.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/laravel.reflection.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/league.configured.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/league.reflection.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/nette-di.compiled.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/phalcon.configured.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/phalcon.configured.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/php-baseline"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/php-di.reflection.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/pimple.configured.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/pimple.configured.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/quickly.compiled.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/quickly.configured.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/quickly.reflection.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/ray-di.compiled.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/ray-di.reflection.transient"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/symfony.compiled.singleton"
      schedule:
          interval: "weekly"
    - package-ecosystem: "composer"
      directory: "/containers/zen.compiled.singleton"
      schedule:
          interval: "weekly"

